// <auto-generated />
using AppdataContext.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Controlator.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231119205826_primeiraMigracao")]
    partial class primeiraMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("model.tablet.Tablet", b =>
                {
                    b.Property<int>("tabletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("imei")
                        .HasColumnType("TEXT");

                    b.Property<string>("modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("plaqueta")
                        .HasColumnType("TEXT");

                    b.HasKey("tabletId");

                    b.ToTable("Tablets");
                });
#pragma warning restore 612, 618
        }
    }
}
